# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamigrate < Formula
  desc "CLI tool for running staged SQL migrations."
  homepage "https://github.com/vszeuszeus/lamigrate"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.10/lamigrate_0.1.10_darwin_amd64.tar.gz"
      sha256 "7aa539022e64a9d1215e4d98e8b91655f731be7803dbc09c588d16ea50038fb3"

      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.10/lamigrate_0.1.10_darwin_arm64.tar.gz"
      sha256 "d887581b97a1563d533e52e51144911b62c133dcbe842959ee57bdd3f59ea417"

      def install
        bin.install "lamigrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.10/lamigrate_0.1.10_linux_amd64.tar.gz"
      sha256 "c919c0f6233bd4c16bdb2db115d1ca4971825fb0718f2731417ee5f53cf8c8fa"
      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.10/lamigrate_0.1.10_linux_arm64.tar.gz"
      sha256 "8bb41bb1470258dd2ebb7630ad2ee2126d292b07b2e0c971efc9e260faab7429"
      def install
        bin.install "lamigrate"
      end
    end
  end

  test do
    system "#{bin}/lamigrate", "version"
  end
end
