# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamigrate < Formula
  desc "CLI tool for running staged SQL migrations."
  homepage "https://github.com/vszeuszeus/lamigrate"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.7/lamigrate_0.1.7_darwin_amd64.tar.gz"
      sha256 "f2aa1c151a8622464f50ad2b2dd4f3725550698a46e538a11410b95a55b4b111"

      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.7/lamigrate_0.1.7_darwin_arm64.tar.gz"
      sha256 "1c217149067d18bcf06693cb934612763d86224719f78dc9b4e6d60a2953351d"

      def install
        bin.install "lamigrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.7/lamigrate_0.1.7_linux_amd64.tar.gz"
      sha256 "e43638b35888aa0bbb450a8393ab13eef5f22d7e2927d14f5bf1e608c11f45ac"
      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.7/lamigrate_0.1.7_linux_arm64.tar.gz"
      sha256 "b706896120c6e536abba0685b217e8eee88c9d83b4522946fcc14686336e5047"
      def install
        bin.install "lamigrate"
      end
    end
  end

  test do
    system "#{bin}/lamigrate", "version"
  end
end
