# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamigrate < Formula
  desc "CLI tool for running staged SQL migrations."
  homepage "https://github.com/vszeuszeus/lamigrate"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.8/lamigrate_0.1.8_darwin_amd64.tar.gz"
      sha256 "7e3600ce3ec40bcdf2407088ee9a0715c0936f5d1184486f021daccde16e23e0"

      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.8/lamigrate_0.1.8_darwin_arm64.tar.gz"
      sha256 "fd362682f71e64c7c5f81ae0ddee35f32839e19c93552bcd92fb7998fee048ad"

      def install
        bin.install "lamigrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.8/lamigrate_0.1.8_linux_amd64.tar.gz"
      sha256 "c490bfd33e6e27f170b2b39d594aa272fec20a8066e1cb80a88aa639bed4e5df"
      def install
        bin.install "lamigrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vszeuszeus/lamigrate/releases/download/v0.1.8/lamigrate_0.1.8_linux_arm64.tar.gz"
      sha256 "dddfb59f1fd61fb843cfdc80816f7c8460720d000dae66ada319226beaef18fb"
      def install
        bin.install "lamigrate"
      end
    end
  end

  test do
    system "#{bin}/lamigrate", "version"
  end
end
